### ISSUE TITLE
Documentation: modules/nixos/luxnix/generic settings

### ISSUE THREAD

**Issue by Maddonix** [wg-lux/luxnix#4]
Task: Add to documentation / reference as this will be frequently required during development and configuration
We implemented a generic settings module.
Here we will store common settings like frequently used paths / paths shared between applications. 

The option is enabled by default and has default values. We can reference these in other parts of the configuration like this:

'variableToSet = config.luxnix.generic-settings.configurationPath' which is defined as option:
```nix
options.luxnix.generic-settings = {
    enable = mkEnableOption "Enable generic settings";
  
    configurationPath = mkOption {
      type = types.path;
      default = "/home/${config.user.admin.name}/luxnix/";
      description = ''
        Path to the luxnix directory.
      '';
    };
};
```

**Comment by maxhild** [comment]
closed, setup in docs/development.md
