### ISSUE TITLE
Documentation Task: Boot Decryption Stick

### ISSUE THREAD

**Issue by Maddonix** [wg-lux/luxnix#7]
added module 'modules/nixos/luxnix/boot-decryption-stick'

-> Provides script to create decryption usb stick
-> run 'sudo boot-decryption-stick-setup'

Important for documentation:
- script generates nix configuration file at systems/x86_64-linux/${hostname}/boot-decryption-config.nix
- this must be imported in system config to be active

Example in gc-06/default.nix 
```nix
{
  pkgs,
  lib,
  ...
}@inputs: 
  let
    sensitiveHdd = import ./sensitive-hdd.nix {};

    extraImports = [
      ./boot-decryption-config.nix
    ];

  in
{
  imports = [
    ./hardware-configuration.nix
    ./disks.nix
  ]++extraImports;
# .....
}
```

**Comment by maxhild** [comment]
added in docs/security
